### ISSUE TITLE
Automate Testing and Release Process

### ISSUE THREAD

**Issue by jkirkpatrick24** [autotelic/fastify-slonik#2]
We should automate our release process in the same way we publish other NPM packages. We can configure a github action in the same way as as [fastify-hmac](https://github.com/autotelic/fastify-hmac/blob/main/.github/workflows/release.yml)

We should also add the `test` github action outlined in that same repo.

**Comment by jkirkpatrick24** [comment]
Related, we should update the plugin template to have these actions by default see -> https://github.com/autotelic/fastify-plugin-template/issues/3#issue-784726203

**Comment by megquirk** [comment]
Added actions: [pull request](https://github.com/autotelic/fastify-slonik/pull/4)

**Comment by jkirkpatrick24** [comment]
Example release workflow -> https://github.com/autotelic/fastify-hmac/blob/main/.github/workflows/release.yml

@matthew-charles-chan can probably help with this as well @meghein
